---
title: "bayes"
format: html
editor: visual
---

```{r}
library(brms)
```


```{r}
all_data %>% 
  mutate(viability_prop= viable_seed_as_percent_of_original / 100) %>% 
  mutate(viability_prop = case_when(
    viability_prop == 1 ~ 0.999,
    viability_prop == 0 ~ 0.001,
    TRUE ~ viability_prop
  )) -> all_data1
```



```{r}
full_model <- bf(
  viability_prop ~ c + (d - c) * exp(- (retrieval_time_months / e)^b),
  b + c + d + e ~ species * depth_cm + (1 | location) + (1 | run) + (1 | location:field_rep),
  nl = TRUE
)
```


```{r}
fit_full <- brm(
  formula = full_model,
  data = all_data1,
  family = Beta(),  # or beta/logit if viability is bounded
  prior = c(
    prior(normal(1, 1), nlpar = "b"),
    prior(normal(0, 10), nlpar = "c"),
    prior(normal(100, 10), nlpar = "d"),
    prior(normal(10, 5), nlpar = "e")
  ),
  save_pars = save_pars(all = TRUE),  
  chains = 4,
  iter = 4000,
  control = list(adapt_delta = 0.95)
)
```

Reduced model without interaction

```{r}
Red_model1 <- bf(
  viability_prop ~ c + (d - c) * exp(- (retrieval_time_months / e)^b),
  b + c + d + e ~ species + (1 | location) + (1 | run) + (1 | location:field_rep),
  nl = TRUE
)
```


```{r}
fit_red1 <- brm(
  formula = full_model,
  data = all_data1,
  family = Beta(),  # or beta/logit if viability is bounded
  prior = c(
    prior(normal(1, 1), nlpar = "b"),
    prior(normal(0, 10), nlpar = "c"),
    prior(normal(100, 10), nlpar = "d"),
    prior(normal(10, 5), nlpar = "e")
  ),
  save_pars = save_pars(all = TRUE),  
  chains = 4,
  iter = 4000,
  control = list(adapt_delta = 0.95)
)
```


```{r}
loo_compare(loo(fit_full), loo(fit_red1))
```

```{r}
bayes_factor(fit_full, fit_red1)
```



```{r}
all_data1$field_rep <- as.factor(all_data1$field_rep)
newdata <- expand.grid(
  retrieval_time_months = seq(0, 60, length.out = 100),  # or 0–36 for run 2
  species = levels(all_data1$species),
  depth_cm = levels(all_data1$depth_cm),
  location = levels(all_data1$location),
  run = levels(all_data1$run),
  field_rep = levels(all_data1$field_rep)
  )
```


```{r}
pred <- fitted(fit_full, newdata = newdata, probs = c(0.025, 0.975))
newdata$estimate <- pred[, "Estimate"]
newdata$lower <- pred[, "Q2.5"]
newdata$upper <- pred[, "Q97.5"]

```



```{r}
ggplot(newdata, aes(x = retrieval_time_months, y = estimate, color = depth_cm)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = depth_cm), color = NA, alpha = 0.2) +
  facet_wrap(~ species) +
  labs(
    title = "Bayesian Weibull Model: Seed Viability Over Time",
    x = "Months of Burial",
    y = "Predicted Viability (%)"
  ) +
  theme_minimal() +
  facet_wrap(run * location ~ species, ncol=3) 

ggsave("bayes.png", width = 8, height = 10)
```















