---
title: "map"
format: html
editor: source
---


```{r}
library(tidyverse)
library(ggspatial)
```


```{r}
tribble(
  ~location, ~latitude, ~longitude,
  "College Station", 30.537130, -96.425917,
  "Corpus Christi", 27.780910, -97.561914,
  "Lubbock", 33.690435, -101.824649
)
```

```{r}
library(tidyverse)
library(sf)
```

```{r}
library(rnaturalearth)
library(rnaturalearthdata)

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```


```{r}
(sites <- tribble(
  ~location, ~latitude, ~longitude,
  "College Station", 30.537130, -96.425917,
  "Corpus Christi", 27.780910, -97.561914,
  "Lubbock", 33.690435, -101.824649
))
```

```{r}
ggplot(data = world) +
    geom_sf() +
    geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = 23, fill = "darkred") +
    coord_sf(xlim = c(-110, -90), ylim = c(36, 25), expand = FALSE)
```

```{r}
library(maps)
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(states)
```

```{r}
invalid <- which(!sf::st_is_valid(states))
invalid
```

```{r}
states <- sf::st_make_valid(states)
```

```{r}
library(sf)

sf_use_s2(FALSE)

states <- cbind(states, st_coordinates(st_centroid(states)))

```




```{r}
library(tools)
states$ID <- toTitleCase(states$ID)
head(states)
```


```{r}
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA) + 
    geom_text(data = states, aes(X, Y, label = ID), size = 5) +
    coord_sf(xlim = c(-107, -93.4), ylim = c(37, 25.5), expand = FALSE) +
    geom_point(data = sites, aes(x = longitude, y = latitude, fill = location), size = 4, 
        shape = c(22,21,23),
        show.legend = FALSE) +
    geom_text(data = sites, aes(x = longitude, y = latitude, label = location),
              nudge_y = -0.5, color = "#333333", fontface = "bold") + 
  theme_map() +
  scale_fill_canva()
```


```{r}
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties <- subset(counties, grepl("texas", counties$ID)) %>% filter(!ID %in% "oklahoma,texas")
counties$area <- as.numeric(st_area(counties))
head(counties)
```

```{r}
ggplot(data = world) +
  geom_sf() +
  geom_sf(data = states, fill = NA, color = "grey80") + 
  geom_sf(data = states, fill = NA) + 
  geom_sf(data = counties, fill = "#FAF9F6", color = gray(.8)) +
  coord_sf(xlim = c(-107, -93.2), ylim = c(37, 25.5), expand = FALSE) +
  geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = c(22,21,23),  fill = c("purple",2,3)) +
  geom_text(data = sites, aes(x = longitude, y = latitude, label = location),
              nudge_y = -0.5, color = "#333333", fontface = "italic") +
  labs(x = NULL, y = NULL) +
  annotate(geom = "text", x = -103.5, y = 27.5, label = "MEXICO", 
           fontface = "bold", color = "grey80", 
           family = "roboto", size = 7) +
  annotate(geom = "text", x = -107, y = 34.5, label = "New Mexico", 
           color = "grey80", 
           family = "roboto", size = 7) +
  annotate(geom = "text", x = -97.4, y = 35.5, label = "Oklahoma", 
           color = "grey80", 
           family = "roboto", size = 7) +
    annotate(geom = "text", x = -92, y = 35, label = "Arkansas", 
           color = "grey80", 
           family = "roboto", size = 7) +
  annotate(geom = "text", x = -99, y = 31.5, label = "Texas", 
           fontface = "bold", color = "grey30", 
           family = "roboto", size = 7) +
  annotate(geom = "text", x = -92.9, y = 27, label = "Gulf of Mexico", 
           color = "#89CFF0", 
           family = "roboto", size = 6) +
  annotation_scale(location = "bl", width_hint = 0.25) +
  annotation_north_arrow(location = "tr", which_north = "true", 
        pad_x = unit(0.1, "in"), pad_y = unit(0.1, "in"),
        style = north_arrow_nautical) +
  theme(panel.background = element_rect(fill = "aliceblue"))
  

    
    

ggsave("figures/map.png", width = 5, height = 5)
```


















# USA

```{r}
usa <- subset(world, admin == "United States of America")
(mainland <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
    geom_sf(data = counties, fill = "cornsilk", color = gray(.5)) +
      geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = c(22,21,23), fill = c(1,2,3)) +
     coord_sf(crs = st_crs(2163), xlim = c(-2500000, 2500000), ylim = c(-2300000, 
         730000)))
```
```{r}
(alaska <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
     coord_sf(crs = st_crs(3467), xlim = c(-2400000, 1600000), ylim = c(200000, 
         2500000), expand = FALSE, datum = NA))
```
```{r}
(hawaii  <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
     coord_sf(crs = st_crs(4135), xlim = c(-161, -154), ylim = c(18, 
         23), expand = FALSE, datum = NA))
```

```{r}
mainland +
 annotation_custom(
      grob = ggplotGrob(alaska),
      xmin = -2750000,
      xmax = -2750000 + (1600000 - (-2400000))/2.5,
      ymin = -2450000,
      ymax = -2450000 + (2500000 - 200000)/2.5
  ) +
  annotation_custom(
      grob = ggplotGrob(hawaii),
      xmin = -1250000,
      xmax = -1250000 + (-154 - (-161))*120000,
      ymin = -2450000,
      ymax = -2450000 + (23 - 18)*120000
  )
```

```{r}
library(cowplot)
(ratioAlaska <- (2500000 - 200000) / (1600000 - (-2400000)))

## [1] 0.575

(ratioHawaii  <- (23 - 18) / (-154 - (-161)))

## [1] 0.7142857

ggdraw(mainland) +
    draw_plot(alaska, width = 0.26, height = 0.26 * 10/6 * ratioAlaska, 
        x = 0.05, y = 0.05) +
    draw_plot(hawaii, width = 0.15, height = 0.15 * 10/6 * ratioHawaii, 
        x = 0.3, y = 0.05)