---
title: "data cleaning"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(readxl)
library(drc)
library(ggthemes)
library(ggtext)
library(broom)
library(patchwork)
```

```{r}
dt1 <- read_excel("data/seed_burial_dt.xlsx", sheet = "6 Months") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor)

dt2 <- read_excel("data/seed_burial_dt.xlsx", sheet = "12 Months") %>% 
  janitor::clean_names() %>% 
  mutate_at(c("viable_seed_as_percent_of_original", "dormancy_level_in_the_seedlot_percent"),
            as.double) %>% 
  mutate_if(is_character, as_factor)

dt3 <- read_excel("data/seed_burial_dt.xlsx", sheet = "24 Months") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor)

dt4 <- read_excel("data/seed_burial_dt.xlsx", sheet = "36 Months") %>% 
  janitor::clean_names() %>% 
  mutate(depth_cm = parse_number(depth_cm)) %>% 
  mutate_if(is_character, as_factor) 

dt5 <- read_excel("data/seed_burial_dt.xlsx", sheet = "36 Months") %>% 
  janitor::clean_names() %>% 
  mutate(depth_cm = parse_number(depth_cm)) %>% 
  mutate_if(is_character, as_factor)

dt6 <- read_excel("data/seed_burial_dt.xlsx", sheet = "48 Months") %>% 
  janitor::clean_names() %>% 
  mutate(depth_cm = parse_number(depth_cm)) %>%
  mutate_if(is_character, as_factor)

dt7 <- read_excel("data/seed_burial_dt.xlsx", sheet = "60 Months") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) %>% 
  mutate(germination_1_6_days = as.double(germination_1_6_days)) %>% 
  dplyr::select(-germination_1_6_days, -germination_2_12_days, -germination_3_20_days) %>% 
  rename(number_seeds_excavated = no_of_seeds_retreived,
         number_seed_germinated = number_seeds_germinated,
         number_dormant_seed_tz = number_dormant_seeds_tz) 
```

```{r}
dt1 %>% 
  bind_rows(dt2) %>% 
  bind_rows(dt3) %>% 
  bind_rows(dt4) %>% 
  bind_rows(dt5) %>% 
  bind_rows(dt6) %>% 
  bind_rows(dt7) %>% 
  mutate(location = case_when(
    location == "CS" ~ "College Station",
    location == "CC" ~ "Corpus Christi",
    location == "LUB" ~ "Lubbock",
    TRUE ~ as_factor(location)
  )) %>% 
  mutate(species = case_when(
    species == "WH" ~ "waterhemp",
    species == "Waterhemp" ~ "waterhemp",
    species == "PA" ~ "Palmer amaranth",
    species == "Palmer" ~ "Palmer amaranth",
    TRUE ~ as_factor(species)
  )) %>% 
  mutate(biotype = case_when(
    species == "Palmer amaranth" & location == "College Station" ~ "amapa1",
    species == "Palmer amaranth" & location == "Corpus Christi" ~ "amapa2",
    species == "Palmer amaranth" & location == "Lubbock" ~ "amapa3",
    species == "waterhemp" & location == "College Station" ~ "amatu1",
    species == "waterhemp" & location == "Corpus Christi" ~ "amatu2",
    species == "waterhemp" & location == "Lubbock" ~ "amatu3",
    TRUE ~ NA_character_
  )) %>% 
  mutate(initial_viab = case_when(
    location == "College Station" & species == "Palmer amaranth" ~ 184,
    location == "Corpus Christi" & species == "Palmer amaranth" ~ 180,
    location == "Lubbock" & species == "Palmer amaranth" ~ 190,
    location == "College Station" & species == "waterhemp" ~ 164,
    location == "Corpus Christi" & species == "waterhemp" ~ 176,
    location == "Lubbock" & species == "waterhemp" ~ 130,
    TRUE ~ NA_real_
  )) %>% 
  mutate_if(is_character, as_factor) -> data
```


```{r}
data %>% 
 group_by(initial_viab, species, biotype, location, depth_cm, field_rep, number_seeds_buried) %>% 
 count() %>% 
 mutate(retrieval_time_months = 0) %>% 
mutate(number_seeds_excavated=200,
       number_seed_germinated=initial_viab,
       number_dormant_seed_tz = number_seeds_buried-initial_viab,
       number_viable_seed=number_seed_germinated,
       total_seed_loss=0,
       seed_loss_decay_futile_germ_percent=0,
       germ_percent = (number_seed_germinated/number_seeds_excavated)*100,
       viability_percent=germ_percent,
       non_viable_percent=100-viability_percent,
       dormancy_percent_in_excavated_seed = (number_dormant_seed_tz/number_seeds_excavated)*100,
       viable_seed_as_percent_of_original=100,
       dormancy_level_in_the_seedlot_percent=dormancy_percent_in_excavated_seed) %>% 
  mutate(viable_seed_as_percent_of_original = 100) %>% 
  dplyr::select(-n) -> at_zero
```


```{r}
data %>% 
  bind_rows(at_zero) %>% 
  mutate(total_seed_loss = if_else(is.na(total_seed_loss), 0, total_seed_loss)) %>% 
  mutate_if(is_character, as_factor) %>% 
  mutate(seed_loss = 200 - total_seed_loss) %>% 
  mutate(run = as_factor("1")) %>% 
  mutate(depth_cm = as_factor(depth_cm)) -> data1
```







```{r}
read_excel("data/seed_burial_phase_ii.xlsx", sheet = "6Months-Phase-II", skip=4) -> p2_6
read_excel("data/seed_burial_phase_ii.xlsx", sheet = "12Months-Phase-II", skip=2) -> p2_12
read_excel("data/seed_burial_phase_ii.xlsx", sheet = "24Months-Phase-II", skip=1) %>% 
  mutate(`Retrieval time` = 24) -> p2_24
```



```{r}
p2_6 %>% 
  bind_rows(p2_12) %>% 
  bind_rows(p2_24) %>% 
  janitor::clean_names() %>% 
  dplyr::select(-phase, -location_3) %>% 
  mutate(initial_viab = case_when(
    species == "Palmer CS" ~ 188,
    species == "Palmer LUB" ~ 182,
    species == "Waterhemp CS" ~ 180,
        TRUE ~ NA_real_
  )) %>% 
  dplyr::select(initial_viab, everything()) %>% 
  rename(location = location_4) -> phase_2_1
```


```{r}
read_excel("data/seed_burial_phase_ii.xlsx", sheet = "36Months-Phase-II", skip=1) %>% 
    janitor::clean_names() %>% 
  mutate(initial_viab = case_when(
    species == "Palmer CS" ~ 188,
    species == "Palmer LUB" ~ 182,
    species == "Waterhemp CS" ~ 180,
    TRUE ~ NA_real_
  )) %>% 
  mutate(number_seeds_excavated = as.double(no_of_total_seeds_retreived)) %>% 
  mutate(total_seed_loss = no_of_seed_in_the_bag - number_seeds_excavated) %>% 
  dplyr::select(initial_viab, retreival_time_months, number_seeds_excavated,
                retreival_time_months, location_4, species, depth, rep, 
                no_of_seed_in_the_bag, number_seeds_excavated, total_seed_loss, total_seed_germinated,
                number_of_total_viable_seed_in_the_bag_at_retrieval_200, no_of_total_seeds_retreived,
                number_viable_seeds_among_non_germinated_tz) %>% 
  rename(retrieval_time = retreival_time_months,
         depth_cm = depth,
         field_rep = rep,
         location = location_4,
         number_seeds_buried = no_of_seed_in_the_bag,
         number_seed_germinated = total_seed_germinated,
         number_viable_seed = number_of_total_viable_seed_in_the_bag_at_retrieval_200) %>% 
  mutate(number_dormant_seed_tz = as.double(number_viable_seeds_among_non_germinated_tz)) %>% 
  mutate(number_seed_germinated = as.double(number_seed_germinated)) %>% 
  mutate(seed_loss_decay_futile_germ_percent = (total_seed_loss / number_seeds_buried)*100) %>% 
  mutate(germ_percent = (number_seed_germinated / number_seeds_excavated) *100) %>% 
  mutate(number_viable_seed = as.double(number_viable_seed),
         number_viable_seed = number_seed_germinated + number_dormant_seed_tz) %>% 
  mutate(viability_percent = (number_viable_seed/number_seeds_excavated)*100) %>% 
  mutate(non_viable_percent = 100 - viability_percent) %>% 
  mutate(dormancy_percent_in_excavated_seed = (number_dormant_seed_tz / number_seeds_excavated)*100) %>% 
  mutate(dormancy_level_in_the_seedlot_percent = (number_dormant_seed_tz/number_seeds_buried)*100) %>% 
  mutate(viable_seed_as_percent_of_original = (number_viable_seed / initial_viab)*100) %>%
  dplyr::select(initial_viab, retrieval_time, location,species, depth_cm, field_rep, number_seeds_buried,
                number_seeds_excavated, number_seed_germinated, number_dormant_seed_tz, number_viable_seed, 
                total_seed_loss, seed_loss_decay_futile_germ_percent, germ_percent, viability_percent,
                non_viable_percent, dormancy_percent_in_excavated_seed, 
                viable_seed_as_percent_of_original, dormancy_level_in_the_seedlot_percent) %>% 
  mutate(depth_cm = parse_number(depth_cm)) -> phase_2_2
```


```{r}
phase_2_1 %>% 
  bind_rows(phase_2_2) %>% 
  mutate(species = case_when(
    species == "Palmer CS" ~ "Palmer amaranth_amapa1",
    species == "Palmer LUB" ~ "Palmer amaranth_amapa3",
    species == "Waterhemp CS" ~ "waterhemp_amatu1",
        TRUE ~ NA_character_
  )) %>% 
  separate(species, into=c("species", "biotype"), sep = "_") %>% 
  mutate_if(is_character, as_factor) %>% 
  rename(retrieval_time_months = retrieval_time) %>% 
  mutate(depth_cm = as_factor(depth_cm)) -> phase_comb
```


```{r}
phase_comb %>% 
  group_by(initial_viab, species, biotype, location, depth_cm, field_rep, number_seeds_buried) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(retrieval_time = 0) %>% 
  mutate(viable_seed_as_percent_of_original = 100,
        number_seeds_excavated = 0,
        total_seed_loss = 0) %>% 
  mutate(number_seed_germinated = case_when(
    species == "Palmer amaranth" ~ 184,
    species == "waterhemp" ~ 164,
    TRUE ~ NA_real_
  )) %>% 
  mutate(number_dormant_seed_tz = number_seeds_buried - number_seed_germinated) %>% 
  mutate(number_viable_seed = number_seed_germinated + number_dormant_seed_tz) %>% 
  mutate(germ_percent = (number_seed_germinated / number_seeds_buried)*100) %>% 
  mutate(viability_percent = 100,
         non_viable_percent = 0,
         dormancy_percent_in_excavated_seed = (number_dormant_seed_tz / number_seeds_buried)*100,
         dormancy_level_in_the_seedlot_percent = dormancy_percent_in_excavated_seed) %>% 
  dplyr::select(-n) %>% 
  rename(retrieval_time_months = retrieval_time) -> at_zero1
```

```{r}
phase_comb %>% 
  bind_rows(at_zero1) %>% 
  mutate(run = as_factor("2")) -> phase2_dt
```






```{r}
data1 %>% 
  bind_rows(phase2_dt) %>% 
  mutate(viability_prop= viable_seed_as_percent_of_original / 100) %>% 
  mutate(viability_prop = case_when(
    viability_prop == 1 ~ 0.999,
    viability_prop == 0 ~ 0.001,
    TRUE ~ viability_prop
  )) %>% 
  mutate(field_rep = as_factor(field_rep)) %>% 
  filter(!is.na(viability_prop)) -> all_data
```


```{r}
all_data %>% 
  count(species, run, depth_cm, location, field_rep)
```



```{r}
#| warning: false
all_data %>% 
  ggplot(aes(x=retrieval_time_months, y=viable_seed_as_percent_of_original,
             color=species)) +
  geom_point() +
  facet_wrap(species~location~run) +
  scale_x_continuous(breaks=c(0, 6, 12, 36)) +
  geom_smooth()


ggsave("test.png", width = 9, height = 7)
```


























